# Generated by Django 3.1.6 on 2021-02-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalshroom',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Specie'},
        ),
        migrations.AlterModelOptions(
            name='shroom',
            options={'verbose_name': 'Specie', 'verbose_name_plural': 'Species'},
        ),
    ]
