# Generated by Django 3.1.6 on 2021-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrooms', '0003_auto_20210210_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshroom',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='shroom',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
