# Generated by Django 3.1.6 on 2021-02-10 16:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indicador',
            new_name='DamageIndicator',
        ),
        migrations.RenameModel(
            old_name='HistoricalIndicador',
            new_name='HistoricalDamageIndicator',
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'Nombre de especie', 'verbose_name_plural': 'Nombres de especies'},
        ),
    ]
