# Generated by Django 3.1.6 on 2021-02-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_auto_20210210_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damageindicator',
            options={'verbose_name': 'Damage indicator', 'verbose_name_plural': 'Damage indicators'},
        ),
        migrations.AlterModelOptions(
            name='historicaldamageindicator',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Damage indicator'},
        ),
        migrations.AlterModelOptions(
            name='historicaltree',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tree Specie'},
        ),
        migrations.AlterModelOptions(
            name='historicaltreefamily',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tree Family'},
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'Tree Specie', 'verbose_name_plural': 'Tree Species'},
        ),
        migrations.AlterModelOptions(
            name='treefamily',
            options={'verbose_name': 'Tree Family', 'verbose_name_plural': 'Tree Families'},
        ),
        migrations.AlterField(
            model_name='damageindicator',
            name='tree_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.treefamily', verbose_name='Family Indicator'),
        ),
        migrations.AlterField(
            model_name='historicaldamageindicator',
            name='tree_family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trees.treefamily', verbose_name='Family Indicator'),
        ),
        migrations.AlterField(
            model_name='historicaltree',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Especie del arbol'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Especie del arbol'),
        ),
    ]
